services:
  api:
    build: .
    container_name: sportstats_api
    comand: poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      #Config de conexão com o banco
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5433/sportstats
    volumes:
      - .:/app
    networks:
      - sportstats_net

  db:
    image: postgres:15
    container_name: sportstats_db
    restart: always
    enviroment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sportstats
    ports:
      - "5432:5433"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - sportstats_net

volumes:
  pg_data:

networks:
  sportstats_net: