services:
  api:
    build: .
    container_name: sportstats_api
    command: poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      #Config de conexão com o banco
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./src:/app/src
    networks:
      - sportstats-net

  db:
    image: postgres:15
    container_name: sportstats_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - sportstats-net

volumes:
  pg_data:

networks:
  sportstats-net:
    driver: bridge